{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Person API",
    "description" : "API for persons",
    "contact" : {
      "name" : "API Support",
      "url" : "http://www.example.com/support",
      "email" : "support@example.com"
    },
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/MARCUSDORON/PersonAPI/1.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "tags" : [ {
    "name" : "persons"
  } ],
  "paths" : {
    "/persons" : {
      "get" : {
        "tags" : [ "persons" ],
        "summary" : "get persons",
        "description" : "Get a list of persons\n",
        "operationId" : "getpersons",
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Persons"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/persons/{name}/" : {
      "get" : {
        "tags" : [ "persons" ],
        "summary" : "get specific person",
        "description" : "Get specific person\n",
        "operationId" : "getperson",
        "parameters" : [ {
          "name" : "name",
          "in" : "path",
          "description" : "person name",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Person"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Persons" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Person"
        }
      },
      "Person" : {
        "required" : [ "firstName", "lastName" ],
        "type" : "object",
        "properties" : {
          "age" : {
            "type" : "integer",
            "format" : "int32"
          },
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          }
        }
      }
    }
  }
}